_wandb:
    value:
        cli_version: 0.28.0
        e:
            cn0hq4ofcs2ebt86uxpwenuxuwm9kjdj:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    macModel: MacBookPro18,3
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                codePath: /Users/sophiali/Desktop/chip-stroma-analysis/notebooks/03_train.ipynb
                codePathLocal: chip-stroma-analysis/notebooks/03_train.ipynb
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "359100293120"
                email: sophiamjiali@gmail.com
                executable: /Users/sophiali/miniconda3/envs/chip-stroma-env/bin/python
                git:
                    commit: 0736c973b4f05d57f2650c6cf6e61c1577cde1b8
                    remote: https://github.com/sophiamjiali/chip-stroma-analysis.git
                host: Sophias-MacBook-Pro-955.local
                memory:
                    total: "17179869184"
                os: macOS-26.5.1-arm64-arm-64bit-Mach-O
                program: /Users/sophiali/Desktop/chip-stroma-analysis/notebooks/03_train.ipynb
                python: CPython 3.14.4
                root: /Users/sophiali/Desktop/chip-stroma-analysis
                startedAt: "2026-06-26T01:11:55.919005Z"
                writerId: cn0hq4ofcs2ebt86uxpwenuxuwm9kjdj
        m: []
        python_version: 3.14.4
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 41
                - 49
                - 53
                - 63
                - 74
                - 80
                - 106
            "2":
                - 1
                - 5
                - 11
                - 35
                - 41
                - 49
                - 53
                - 63
                - 74
                - 80
                - 106
            "3":
                - 2
                - 13
                - 16
            "4": 3.14.4
            "5": 0.28.0
            "6": 5.8.1
            "8":
                - 1
            "12": 0.28.0
            "13": darwin-arm64
T_max:
    value: 10
ftl_alpha:
    value: 0.3
ftl_beta:
    value: 0.7
ftl_gamma:
    value: 0.75
ftl_weight:
    value: 0.5
lr:
    value: "1e-4"
smooth:
    value: 1
weight_decay:
    value: "1e-2"
