# ==============================================================================
# Script:           paths.yaml
# Purpose:          Input and output paths for the full pipeline
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             06/04/2026
# ==============================================================================

# Normalized and name-sanitized patches and masks
processed_data:
  processed_dir  : data/test_data
  patch_dir      : data/test_data/patches
  vessel_mask_dir: data/test_data/vessel_masks
  tissue_mask_dir: data/test_data/tissue_masks

metadata:
  chip_labels     : data/from_hpc/metadata/CHIP_IDs.csv
  name_mapping    : data/from_hpc/metadata/name_mapping.json
  patch_manifest  : data/test_data/metadata/patch_manifest.csv
  patch_statistics: data/from_hpc/metadata/patch_statistics.csv  # didn't convert yet
  train_manifest  : data/test_data/metadata/train_manifest.csv   # include == True

# Training and sweep output directories
outputs:
  training: outputs/training
  sweeps  : outputs/sweeps

# Key results from the full pipeline
results:
  masks:
    fibroblasts_dir: results/masks/fibroblasts
    vessels_dir    : results/masks/vessels
  overlays:
    fibroblasts_dir: results/overlays/fibroblasts
    vessels_dir    : results/overlays/vessels

# [END]