# ==============================================================================
# Script:           paths.yaml
# Purpose:          Input and output paths for the full pipeline
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             06/04/2026
# ==============================================================================


# Normalized and name-sanitized patches and masks
processed_data:
  processed_dir  : /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data
  patch_dir      : /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data/patches
  vessel_mask_dir: /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data/vessel_masks
  tissue_mask_dir: /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data/tissue_masks

metadata:
  chip_labels     : /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data/metadata/CHIP_IDs.csv
  name_mapping    : /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data/metadata/nname_mapping.json
  patch_manifest  : /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data/metadata/patch_manifest.csv
  patch_statistics: /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data/metadata/patch_statistics.csv
  train_manifest  : /cluster/projects/kumargroup/sophia/chip-stroma-analysis/data/metadata/train_manifest.csv    # Only include = True

# Training and sweep output directories
outputs:
  checkpoints: outputs/checkpoints
  training: outputs/training
  sweeps  : outputs/sweeps
  studies: /cluster/home/t144807uhn/chip-stroma-analysis/studies

# Key results from the full pipeline
results:
  masks:
    fibroblasts_dir: results/masks/fibroblasts
    vessels_dir    : results/masks/vessels
  overlays:
    fibroblasts_dir: results/overlays/fibroblasts
    vessels_dir    : results/overlays/vessels

# [END]