# ==============================================================================
# Script:           segmentation.yaml
# Purpose:          U-Net hyperparameters, augmentation, and training
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             06/03/2026
# ==============================================================================

seed: 42