# ==============================================================================
# Script:           segmentation_sweep.yaml
# Purpose:          WandB sweep configurations
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             06/03/2026
# ==============================================================================