# ==============================================================================
# Script:           cross_validation.yaml
# Purpose:          Patient-stratified K-Fold CV Parameters
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             06/22/2026
# ==============================================================================

seed: 42
positive_label: CH
negative_label: NC
k: 5
n_pos_bins: 2