# ==============================================================================
# Script:           07_evaluate.yaml
# Purpose:          Evaluation and statistics generation configurations
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             07/22/2026
# ==============================================================================

val_fold: 0

batch_size: 32
n_workers: 4

model:
  encoder_name   : resnet34
  encoder_weights: imagenet
  in_channels    : 3
  out_classes    : 1