# ==============================================================================
# Script:           09_visualize.yaml
# Purpose:          Evaluation and statistics generation configurations
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             07/24/2026
# ==============================================================================

fold_boxplot_metric: "dice"
highlight_patient  : "h-BMO-18"