# ==============================================================================
# Script:           11_analysis.yaml
# Purpose:          General analysis parameters
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             08/05/2026
# ==============================================================================

vessel_threshold: 0.5
min_object_threshold: 5