# ==============================================================================
# Script:           12_analysis.yaml
# Purpose:          General analysis parameters
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             08/26/2026
# ==============================================================================

vessel_threshold: 0.5
colours: [0, 1, 2]