# ==============================================================================
# Script:           12_analysis.yaml
# Purpose:          General analysis parameters
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             08/26/2026
# ==============================================================================

vessel_threshold: 0.5
colours:
  vessel:     [0, 255, 0]     # lime, matches save_overlay_masks palette
  fibroblast: [255, 0, 0]     # red
  tissue:     [128, 128, 128] # gray