# ==============================================================================
# Script:           paths.yaml
# Purpose:          Preprocessing parameters
# Author:           Sophia Mengjia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             06/04/2026
# ==============================================================================

tissue_detection:
  tissue_threshold: 0.5
  gaussian_sigma: 1.0
  min_region_size: 500
  morph_disk_radius: 3

artifact_detection:
  blur_threshold: 100.0
  dark_pixel_threshold: 50
  dark_pixel_ratio: 0.1
  pen_pixel_ratio: 0.05

normalization:
  reference_patch: ...
  method: vahadane